### ISSUE TITLE
Package unusable with k8s deployment+ingress+tls termination

### ISSUE THREAD

**Issue by alee-x** [camunda-community-hub/zeebe-client-csharp#696]
**Describe the bug**
This package cannot be used when Zeebe Gateway is deployed on Kubernetes, exposed via an Ingress secured with TLS, with TLS terminating at the Ingress and not the pod. 

When using a K8s Ingress with GRPC protocol, http2 can only be served over port 443 (see [this issue](https://github.com/kubernetes/ingress-nginx/issues/6736) or [this issue](https://github.com/kubernetes/ingress-nginx/issues/6313), meaning that the Ingress has to use TLS. The generally accepted solution in this case is that you then terminate TLS at the Ingress and allow plain text communication between the pod and the ingress controller.

This pattern would result in a Zeebe Gateway URL that looks like `https://zeebe-gateway-grpc.my.ingress.controller`, but the fact we're terminating TLS at the edge means the client needs to be instantiated with `.UsePlainText()`.

However, two pieces of behaviour stop this from working:

1. The [https://github.com/camunda-community-hub/zeebe-client-csharp/blob/main/Client/Impl/Builder/ZeebeClientBuilder.cs#L54-L58](ZeebePlainClientBuilder) does not allow plain clients to be created when using a https protocol on the Zeebe URL.
2. The [https://github.com/camunda-community-hub/zeebe-client-csharp/blob/main/Client/ZeebeClient.cs#L85](ZeebeClient) always assumes that there are credentials when using https.

The workaround is to expose the Zeebe Gateway using an external Load Balancer so it gets an IP, _however_ in cloud deployments (AWS, AKS, etc) ELBs are much more expensive than Ingress controllers and are generally more hassle. 

**To Reproduce**
1. Deploy the `camunda-platform` helm chart on a K8s cluster with an ingress controller, in the values.yaml file you'll need to add:
```
zeebeGateway:
  ingress:
    grpc:
      enabled: true
      className: "YOUR NGINX CONTROLLER CLASS NAME HERE"
      host: "grpc-zeebe-gateway.your.domain.address"
      annotations:
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      tls:
        enabled: true
        secretName: camunda-platform-zeebe-gateway-grpc
```
(this assumes that you have already created a tls secret with correct certs and keys called `camunda-platform-zeebe-gateway-grpc`)
2. Using the [https://github.com/camunda-community-hub/zeebe-client-csharp/blob/main/Client.Examples/Program.cs#L30](Client.Examples), change the ZeebeUrl to `https://<whatever you just put as the ingress host>` and leave `.UsePlainText()`. 
4. Watch it fail.

**Expected behavior**
I should be able to configure the client to use both a https URL and plaintext for cases where TLS is terminated at the edge.

**Enviroment (please complete the following information):**
 - Kubernetes version: v1.28.2+k3s1
 - ingress-nginx: 4.10.1
 - this client version: 2.6.0
